### ISSUE TITLE
Allow no-input

### ISSUE THREAD

**Issue by simon-virkesborsen** [dduong42/s3manifestcollectstatic#4]
Missing option for `--no-input` as seen on the standard `collectstatic` command

I can implement this but wanted an issue to confirm this is not possible currently

**Comment by dduong42** [comment]
Is it necessary? I don't think the command asks for any input (or my memory could be wrong).

**Comment by 28140** [comment]
> I don't think the command asks for any input (or my memory could be wrong).

Lately it does.

New behaviour for s3manifestcollectstatic:

When I run `python manage.py s3manifestcollectstatic -w 20 -v 2 --settings=config.settings.production` on my production machine I get the following message:

```
You have requested to collect static files at the destination
location as specified in your settings.

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: no

```
I’m using Python 3.11.4, Django 4.2.4 with the following settings:

config.settings.production:

```
STORAGES = {
    "default": {
        "BACKEND": "company.utils.storages.MediaRootS3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "company.utils.storages.StaticRootS3Boto3Storage",
    },
}
```

And here is my company.utils.storages:

```
from storages.backends.s3boto3 import S3ManifestStaticStorage, S3Boto3Storage

class MediaRootS3Boto3Storage(S3Boto3Storage):
    bucket_name = "company"
    location = "media"
    default_acl = "public-read"
    file_overwrite = True
    custom_domain = “company.fra1.cdn.digitaloceanspaces.com"

class StaticRootS3Boto3Storage(S3ManifestStaticStorage):
    bucket_name = "company"
    location = "static"
    default_acl = "public-read"
    file_overwrite = True
    custom_domain = "company.fra1.cdn.digitaloceanspaces.com"

```

Thanks, @dduong42.

**Comment by dduong42** [comment]
@28140 Are you using the last version of the package? I'm not able to reproduce this locally.

Let's take a look at [Django's code](https://github.com/django/django/blob/6f4c7c124a03f7b01d868cb7d1fa55564b5f2bf8/django/contrib/staticfiles/management/commands/collectstatic.py#L190):
```python
        message.append(
            "You have requested to collect static files at the destination\n"
            "location as specified in your settings"
        )

        if self.is_local_storage() and self.storage.location:
            destination_path = self.storage.location
            message.append(":\n\n    %s\n\n" % destination_path)
            should_warn_user = self.storage.exists(destination_path) and any(
                self.storage.listdir(destination_path)
            )
        else:
            destination_path = None
            message.append(".\n\n")
            # Destination files existence not checked; play it safe and warn.
            should_warn_user = True

        if self.interactive and should_warn_user:
            if self.clear:
                message.append("This will DELETE ALL FILES in this location!\n")
            else:
                message.append("This will overwrite existing files!\n")

            message.append(
                "Are you sure you want to do this?\n\n"
                "Type 'yes' to continue, or 'no' to cancel: "
            )
            if input("".join(message)) != "yes":
                raise CommandError("Collecting static files cancelled.")
```

You're receiving this message because either `self.is_local_storage()` is `False` or `self.storage.location` is falsy. Which would somehow means that `override_storage_settings` doesn't do its job, and we're not collecting your current static files into a temporary directory before sending them to S3.

Can you try to dig a little bit deeper?

**Comment by 28140** [comment]
@dduong42 Yes, I'm using the latest version, 0.3.1.

Thank you for looking into it.

Here’s what I’ve found.

Instead of this:

```
@staticmethod
@contextmanager
def override_storage_settings(static_root, staticfiles_storage):
    saved_static_root = settings.STATIC_ROOT
    settings.STATIC_ROOT = static_root

    if VERSION < (4, 2) or settings.is_overridden("STATICFILES_STORAGE"):
        saved_storage = settings.STATICFILES_STORAGE
        settings.STATICFILES_STORAGE = staticfiles_storage
        yield
        settings.STATICFILES_STORAGE = saved_storage
    else:
        saved_storage = settings.STORAGES
        settings.STORAGES = {
            **saved_storage,
            "staticfiles": {
                "BACKEND": staticfiles_storage,
            },
        }
        yield
        settings.STORAGES = saved_storage

    settings.STATIC_ROOT = saved_static_root
```

We should be doing this:

```
@staticmethod
@contextmanager
def override_storage_settings(static_root, staticfiles_storage):
    saved_static_root = settings.STATIC_ROOT
    settings.STATIC_ROOT = static_root

    if VERSION < (4, 2) or settings.is_overridden("STATICFILES_STORAGE"):
        saved_storage = settings.STATICFILES_STORAGE
        settings.STATICFILES_STORAGE = staticfiles_storage
        yield
        settings.STATICFILES_STORAGE = saved_storage
    else:
        saved_static_storage = settings.STORAGES["staticfiles"]["BACKEND"]
        settings.STORAGES["staticfiles"]["BACKEND"] = staticfiles_storage
        yield
        settings.STORAGES["staticfiles"]["BACKEND"] = saved_static_storage

    settings.STATIC_ROOT = saved_static_root
```

But isn’t it the same thing, I hear you say?

Yes, it is, I know…

But somehow it isn’t.

Go ahead, try it for yourself, sprinkle some prints in `django/contrib/staticfiles/management/commands/collectstatic.py`…

I’d recommend the following, @ line 183, just before the code snippet you gave me earlier:

```
print("STORAGE:", self.storage)
print("STORAGE_LOCATION:", self.storage.location)
print("IS_LOCAL_STORAGE:", self.is_local_storage())
```

[https://github.com/django/django/blob/6f4c7c124a03f7b01d868cb7d1fa55564b5f2bf8/django/contrib/staticfiles/management/commands/collectstatic.py#L183](https://github.com/django/django/blob/6f4c7c124a03f7b01d868cb7d1fa55564b5f2bf8/django/contrib/staticfiles/management/commands/collectstatic.py#L183)

And then try with both the current version and my above version of `override_storage_settings()`.

The difference between the runs is this:

0.3.1:
```
STORAGE: <company.utils.storages.StaticRootS3Boto3Storage object at 0x10c9e3c10>
STORAGE_LOCATION: static
IS_LOCAL_STORAGE: False
```

My version:
```
STORAGE: <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x1163958d0>
STORAGE_LOCATION: /var/folders/08/ymgy8x0n0t7drpc454fzvsj00000gn/T/tmplkp1w9wp
IS_LOCAL_STORAGE: True
```

So `collectstatic` tries to write the files remotely instead of writing them into a `TemporaryDirectory()`…

That’s why you’re saying that `self.is_local_storage()` is `False`, because it is (when it shouldn’t be).

And that’s why the message from `collectstatic` (which shouldn’t appear).

Looking forward to your reply.

Thanks!

**Comment by dduong42** [comment]
@28140 Can you take a look at #5 and see if it fixes your problem?

**Comment by 28140** [comment]
@dduong42 Yes, it does, thank you!
